# Auto-labeler configuration
# https://github.com/actions/labeler

frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**/*'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

k8s:
  - changed-files:
      - any-glob-to-any-file: 'k8s/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'frontend/tests/**/*'
          - '**/*.spec.ts'
          - '**/*.test.ts'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/package.json'
          - '**/pnpm-lock.yaml'

security:
  - changed-files:
      - any-glob-to-any-file:
          - '**/auth/**/*'
          - '**/*sentry*'
          - '**/*security*'

components:
  - changed-files:
      - any-glob-to-any-file: 'frontend/components/**/*'

pages:
  - changed-files:
      - any-glob-to-any-file: 'frontend/pages/**/*'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.config.ts'
          - '**/*.config.js'
          - '**/*.config.mjs'
