FROM python:3.10
WORKDIR /app
ADD . /app
COPY requirement.txt .
RUN pip install -r requirement.txt
RUN test -d ./img || mkdir ./img && chmod -R 777 ./img
COPY . .

ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_APP=app.py
ENV FLASK_ENV=development
EXPOSE 3000
CMD ["flask", "run", "--host=0.0.0.0", "--port=3000", "--debug"]
