"""add ai model control value

Revision ID: 1bed8c5c5cdf
Revises: de3118b675c3
Create Date: 2025-08-15 13:41:49.431752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bed8c5c5cdf'
down_revision = 'de3118b675c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AI_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_training', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_be_updated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AI_models', schema=None) as batch_op:
        batch_op.drop_column('can_be_updated')
        batch_op.drop_column('is_training')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
