"""increase the accuracy of ru position

Revision ID: d4b4769bf511
Revises: 1bed8c5c5cdf
Create Date: 2025-08-28 10:26:40.295287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4b4769bf511'
down_revision = '1bed8c5c5cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RU_caches', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=False)
        batch_op.alter_column('lon',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=False)
        batch_op.alter_column('z',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=False)

    with op.batch_alter_table('RUs', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=False)
        batch_op.alter_column('lon',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=False)
        batch_op.alter_column('z',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               nullable=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('rotation_offset',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
        batch_op.alter_column('lat_offset',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
        batch_op.alter_column('lon_offset',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)
        batch_op.alter_column('scale',
               existing_type=mysql.FLOAT(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('scale',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('lon_offset',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('lat_offset',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('rotation_offset',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('RUs', schema=None) as batch_op:
        batch_op.alter_column('z',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('RU_caches', schema=None) as batch_op:
        batch_op.alter_column('z',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lon',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lat',
               existing_type=sa.Double(),
               type_=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
