"""add ai_metrics table

Revision ID: d885206969e3
Revises: 9afad3f08c9a
Create Date: 2025-08-12 08:31:05.887286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd885206969e3'
down_revision = '9afad3f08c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('ai_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('abstract_metrics_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['abstract_metrics_id'], ['abstract_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['primitive_AI_models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('api_source', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('abstract_metrics_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abstract_metrics_id'], ['abstract_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ran_device_metrics')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['brand_name'])

    with op.batch_alter_table('primitive_AI_models', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['model_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('primitive_AI_models', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('ran_device_metrics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_or_AI_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('interval', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('api_source', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('operator', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('brand_metrics')
    op.drop_table('ai_metrics')
    op.drop_table('abstract_metrics')
    # ### end Alembic commands ###
