<template>
  <div class="ai-simulator-page">
    <div class="page-header">
      <h1 class="page-title">AI Application Simulator</h1>
      <!-- 警告橫幅 (Figma 277:986) -->
      <div class="warning-banner">
        <v-icon color="warning" size="20">mdi-alert-circle</v-icon>
        <span>Note: All data is generated by the simulator.</span>
      </div>
    </div>

    <div class="page-content">
      <!-- 左側面板：Model List 或 NES 控制面板 -->
      <div class="left-panel">
        <!-- Model List 視圖 -->
        <template v-if="!selectedModel">
          <div class="panel-header">Model list</div>
          <div class="model-buttons">
            <v-btn
              v-for="model in modelList"
              :key="model.id"
              color="success"
              variant="elevated"
              class="model-btn"
              @click="selectModel(model.id)"
            >
              {{ model.name }}
            </v-btn>
          </div>
        </template>

        <!-- NES Model 控制面板 (Figma 277:465) -->
        <template v-else-if="selectedModel === 'nes'">
          <div class="panel-header">NES</div>
          <div class="nes-controls">
            <v-select
              v-model="nesModelSelect"
              :items="nesModelOptions"
              label="Model Select"
              density="compact"
              variant="outlined"
              class="model-select"
              hide-details
            />
            <v-btn
              :color="nesModelSelect ? 'success' : 'default'"
              :disabled="!nesModelSelect || trainingStatus === 'running'"
              variant="elevated"
              class="control-btn"
              @click="startPreTrain"
            >
              Pre-train
            </v-btn>
            <v-btn
              :color="trainingStatus === 'finish' ? 'warning' : 'default'"
              :disabled="trainingStatus !== 'finish'"
              variant="elevated"
              class="control-btn"
              @click="showPreview"
            >
              Preview
            </v-btn>
          </div>
          <div class="panel-actions">
            <v-btn color="primary" variant="outlined" class="action-btn" @click="goBack">
              BACK
            </v-btn>
            <v-btn
              v-if="trainingStatus === 'running'"
              color="error"
              variant="elevated"
              class="action-btn"
              @click="stopTraining"
            >
              STOP
            </v-btn>
            <v-btn
              v-else-if="trainingStatus === 'finish'"
              color="primary"
              variant="elevated"
              class="action-btn"
              @click="updateModel"
            >
              Update
            </v-btn>
            <v-btn
              v-else
              color="primary"
              variant="elevated"
              class="action-btn"
              @click="startTraining"
            >
              START
            </v-btn>
          </div>
        </template>

        <!-- 其他模型 placeholder -->
        <template v-else>
          <div class="panel-header">{{ selectedModel.toUpperCase() }}</div>
          <div class="placeholder-content">
            <v-icon size="48" color="grey">mdi-cog</v-icon>
            <p class="text-grey">功能開發中</p>
          </div>
          <div class="panel-actions">
            <v-btn color="primary" variant="outlined" class="action-btn" @click="goBack">
              BACK
            </v-btn>
          </div>
        </template>
      </div>

      <!-- 右側面板：Scene 或 Pre-Train Process -->
      <div class="right-panel">
        <!-- Scene 視圖 (無訓練時) -->
        <template v-if="trainingStatus !== 'running' && trainingStatus !== 'finish'">
          <div class="panel-header">Scene</div>
          <div class="map-container">
            <div id="aiSimulatorMap" class="map-view" />
            <!-- 色標 -->
            <div v-show="showHeatmap" class="color-bar">
              <div class="color-gradient" />
              <div class="color-labels">
                <span>-59.8 dBm</span>
                <span>-140.0 dBm</span>
              </div>
            </div>
            <!-- Heatmap 控制 -->
            <div class="heatmap-control">
              <v-switch
                v-model="showHeatmap"
                label="Heatmap"
                density="compact"
                hide-details
                class="heatmap-switch"
              />
              <v-select
                v-model="heatmapType"
                :items="['RSRP']"
                density="compact"
                class="heatmap-select"
                hide-details
              />
            </div>
          </div>
        </template>

        <!-- Pre-Train Process 視圖 (Figma 277:383) -->
        <template v-else>
          <div class="panel-header">
            Pre-Train Process
            <span :class="['training-status', trainingStatus]">
              Training Status : {{ trainingStatus }}
            </span>
          </div>
          <div class="training-content">
            <!-- 訓練圖表區域 -->
            <div class="charts-section">
              <!-- 主圖表：Reward over Epochs -->
              <div class="chart-container main-chart">
                <p class="chart-title">Reward over Epochs (with MA10)</p>
                <div class="chart-wrapper">
                  <canvas ref="rewardChartRef" />
                </div>
              </div>
              <!-- 底部兩個小圖表 -->
              <div class="charts-row">
                <div class="chart-container">
                  <p class="chart-title">Critic Loss over Epochs</p>
                  <div class="chart-wrapper small">
                    <canvas ref="criticLossChartRef" />
                  </div>
                </div>
                <div class="chart-container">
                  <p class="chart-title">Actor Loss over Epochs</p>
                  <div class="chart-wrapper small">
                    <canvas ref="actorLossChartRef" />
                  </div>
                </div>
              </div>
            </div>
            <!-- 訓練資訊 -->
            <div class="training-info">
              <p class="info-item highlight">Loss Function : Self-defined</p>
              <p class="info-item">Epoch: {{ trainingEpoch }}/1000</p>
              <div class="results-section">
                <p class="results-title">Training Results:</p>
                <p class="result-item">Reward: {{ trainingResults.reward.toFixed(2) }}</p>
                <p class="result-item">Actor Loss: {{ trainingResults.actorLoss.toFixed(1) }}</p>
                <p class="result-item">Critic Loss: {{ trainingResults.criticLoss.toFixed(3) }}</p>
              </div>
            </div>
          </div>
        </template>
      </div>
    </div>

    <!-- 提示訊息 -->
    <v-snackbar v-model="snackbar.show" :color="snackbar.color" timeout="3000" location="top">
      {{ snackbar.text }}
    </v-snackbar>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, nextTick, shallowRef } from 'vue'
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'
import {
  Chart,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  LineController
} from 'chart.js'

// 註冊 Chart.js 組件
Chart.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  LineController
)

const config = useRuntimeConfig()
const isOnline = config.public?.isOnline

// 地圖相關
let map: mapboxgl.Map | null = null
const mapAccessToken = 'pk.eyJ1IjoiZGFyaXVzbHVuZyIsImEiOiJjbHk3MWhvZW4wMTl6MmlxMnVhNzI3cW0yIn0.WGvtamOAfwfk3Ha4KsL3BQ'
const onlineStyle = 'mapbox://styles/mapbox/streets-v12'
const offlineStyle = config.public?.offlineMapboxGLJSURL

// Model 列表 (Figma 277:952)
const modelList = [
  { id: 'nes', name: 'NES' },
  { id: 'positioning', name: 'Positioning' },
  { id: 'im', name: 'IM' },
  { id: 'mro', name: 'MRO' },
  { id: 'rs', name: 'RS' },
  { id: 'bc', name: 'BC' }
]

const selectedModel = ref<string | null>(null)

// NES Model 控制 (Figma 277:465)
const nesModelSelect = ref<string | null>(null)
const nesModelOptions = ['Model 1', 'Model 2', 'Model 3']

// 訓練狀態
type TrainingStatus = 'idle' | 'running' | 'finish'
const trainingStatus = ref<TrainingStatus>('idle')
const trainingEpoch = ref(0)
const trainingResults = ref({
  reward: 0,
  actorLoss: 0,
  criticLoss: 0
})

// 圖表 refs
const rewardChartRef = ref<HTMLCanvasElement | null>(null)
const criticLossChartRef = ref<HTMLCanvasElement | null>(null)
const actorLossChartRef = ref<HTMLCanvasElement | null>(null)

// Chart.js 實例 (使用 shallowRef 避免深度響應)
const rewardChart = shallowRef<Chart | null>(null)
const criticLossChart = shallowRef<Chart | null>(null)
const actorLossChart = shallowRef<Chart | null>(null)

// 訓練數據存儲
const trainingData = ref({
  epochs: [] as number[],
  rewards: [] as number[],
  rewardsMA10: [] as number[],
  bestRewards: [] as number[],
  bestRewardsMA10: [] as number[],
  criticLosses: [] as number[],
  actorLosses: [] as number[]
})

// Heatmap 控制
const showHeatmap = ref(false)
const heatmapType = ref('RSRP')

const snackbar = ref({ show: false, text: '', color: 'info' })

// 計算移動平均 (MA10)
function calculateMA(data: number[], windowSize: number = 10): number[] {
  const result: number[] = []
  for (let i = 0; i < data.length; i++) {
    if (i < windowSize - 1) {
      // 數據不足時，使用可用數據的平均
      const slice = data.slice(0, i + 1)
      result.push(slice.reduce((a, b) => a + b, 0) / slice.length)
    } else {
      const slice = data.slice(i - windowSize + 1, i + 1)
      result.push(slice.reduce((a, b) => a + b, 0) / windowSize)
    }
  }
  return result
}

// 初始化圖表
function initCharts() {
  destroyCharts()

  nextTick(() => {
    // Reward 圖表 (主圖表，4 條線)
    if (rewardChartRef.value) {
      const ctx = rewardChartRef.value.getContext('2d')
      if (ctx) {
        rewardChart.value = new Chart(ctx, {
          type: 'line',
          data: {
            labels: [],
            datasets: [
              {
                label: 'reward',
                data: [],
                borderColor: '#2196F3',
                backgroundColor: 'transparent',
                borderWidth: 1,
                pointRadius: 0,
                tension: 0.1
              },
              {
                label: 'reward (MA10)',
                data: [],
                borderColor: '#64B5F6',
                backgroundColor: 'transparent',
                borderWidth: 2,
                pointRadius: 0,
                tension: 0.3
              },
              {
                label: 'bestReward',
                data: [],
                borderColor: '#4CAF50',
                backgroundColor: 'transparent',
                borderWidth: 1,
                pointRadius: 0,
                tension: 0.1
              },
              {
                label: 'bestReward (MA10)',
                data: [],
                borderColor: '#FFD600',
                backgroundColor: 'transparent',
                borderWidth: 2,
                pointRadius: 0,
                tension: 0.3
              }
            ]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            animation: false,
            scales: {
              x: {
                title: { display: true, text: 'epoch', font: { size: 10 } },
                ticks: { font: { size: 9 }, maxTicksLimit: 6 }
              },
              y: {
                title: { display: true, text: 'value', font: { size: 10 } },
                ticks: { font: { size: 9 } },
                min: 0.4,
                max: 1.1
              }
            },
            plugins: {
              legend: {
                position: 'bottom',
                labels: { font: { size: 9 }, boxWidth: 20, padding: 8 }
              },
              tooltip: { enabled: true, mode: 'index', intersect: false }
            }
          }
        })
      }
    }

    // Critic Loss 圖表 (左下)
    if (criticLossChartRef.value) {
      const ctx = criticLossChartRef.value.getContext('2d')
      if (ctx) {
        criticLossChart.value = new Chart(ctx, {
          type: 'line',
          data: {
            labels: [],
            datasets: [{
              label: 'critic_loss',
              data: [],
              borderColor: '#FFC107',
              backgroundColor: 'transparent',
              borderWidth: 1.5,
              pointRadius: 0,
              tension: 0.1
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            animation: false,
            scales: {
              x: {
                title: { display: true, text: 'epoch', font: { size: 9 } },
                ticks: { font: { size: 8 }, maxTicksLimit: 5 }
              },
              y: {
                title: { display: true, text: 'critic_loss', font: { size: 9 } },
                ticks: { font: { size: 8 } }
              }
            },
            plugins: {
              legend: { display: false },
              tooltip: { enabled: true }
            }
          }
        })
      }
    }

    // Actor Loss 圖表 (右下)
    if (actorLossChartRef.value) {
      const ctx = actorLossChartRef.value.getContext('2d')
      if (ctx) {
        actorLossChart.value = new Chart(ctx, {
          type: 'line',
          data: {
            labels: [],
            datasets: [{
              label: 'actor_loss',
              data: [],
              borderColor: '#FF9800',
              backgroundColor: 'transparent',
              borderWidth: 1.5,
              pointRadius: 0,
              tension: 0.1
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            animation: false,
            scales: {
              x: {
                title: { display: true, text: 'epoch', font: { size: 9 } },
                ticks: { font: { size: 8 }, maxTicksLimit: 5 }
              },
              y: {
                title: { display: true, text: 'actor_loss', font: { size: 9 } },
                ticks: { font: { size: 8 } }
              }
            },
            plugins: {
              legend: { display: false },
              tooltip: { enabled: true }
            }
          }
        })
      }
    }
  })
}

// 銷毀圖表
function destroyCharts() {
  if (rewardChart.value) {
    rewardChart.value.destroy()
    rewardChart.value = null
  }
  if (criticLossChart.value) {
    criticLossChart.value.destroy()
    criticLossChart.value = null
  }
  if (actorLossChart.value) {
    actorLossChart.value.destroy()
    actorLossChart.value = null
  }
}

// 更新圖表數據
function updateCharts() {
  const data = trainingData.value

  // 更新 Reward 圖表
  if (rewardChart.value) {
    rewardChart.value.data.labels = data.epochs
    rewardChart.value.data.datasets[0].data = data.rewards
    rewardChart.value.data.datasets[1].data = data.rewardsMA10
    rewardChart.value.data.datasets[2].data = data.bestRewards
    rewardChart.value.data.datasets[3].data = data.bestRewardsMA10
    rewardChart.value.update('none')
  }

  // 更新 Critic Loss 圖表
  if (criticLossChart.value) {
    criticLossChart.value.data.labels = data.epochs
    criticLossChart.value.data.datasets[0].data = data.criticLosses
    criticLossChart.value.update('none')
  }

  // 更新 Actor Loss 圖表
  if (actorLossChart.value) {
    actorLossChart.value.data.labels = data.epochs
    actorLossChart.value.data.datasets[0].data = data.actorLosses
    actorLossChart.value.update('none')
  }
}

// 重置訓練數據
function resetTrainingData() {
  trainingData.value = {
    epochs: [],
    rewards: [],
    rewardsMA10: [],
    bestRewards: [],
    bestRewardsMA10: [],
    criticLosses: [],
    actorLosses: []
  }
}

// 選擇模型
function selectModel(modelId: string) {
  selectedModel.value = modelId
  trainingStatus.value = 'idle'
  trainingEpoch.value = 0
  nesModelSelect.value = null
  resetTrainingData()
}

// 返回 Model List
function goBack() {
  selectedModel.value = null
  trainingStatus.value = 'idle'
  trainingEpoch.value = 0
  nesModelSelect.value = null
  resetTrainingData()
  destroyCharts()
  // 重新初始化地圖
  nextTick(() => initializeMap())
}

// 開始預訓練 (Pre-train 按鈕)
function startPreTrain() {
  if (!nesModelSelect.value) return
  snackbar.value = {
    show: true,
    text: 'Pre-train 功能尚未實作 (需後端 API: POST /ai-simulator/pretrain/start)',
    color: 'warning'
  }
}

// 開始訓練 (START 按鈕)
function startTraining() {
  if (!nesModelSelect.value) {
    snackbar.value = {
      show: true,
      text: '請先選擇模型',
      color: 'warning'
    }
    return
  }

  trainingStatus.value = 'running'
  trainingEpoch.value = 0
  resetTrainingData()

  // 初始化圖表
  nextTick(() => {
    initCharts()
    // 開始模擬訓練
    nextTick(() => simulateTraining())
  })
}

// 停止訓練
function stopTraining() {
  if (trainingInterval) {
    clearInterval(trainingInterval)
    trainingInterval = null
  }
  trainingStatus.value = 'idle'
  snackbar.value = {
    show: true,
    text: '訓練已停止',
    color: 'info'
  }
}

// 更新模型
function updateModel() {
  snackbar.value = {
    show: true,
    text: 'Update 功能尚未實作 (需後端 API: POST /ai-simulator/pretrain/update)',
    color: 'warning'
  }
}

// 顯示預覽
function showPreview() {
  snackbar.value = {
    show: true,
    text: 'Preview 功能尚未實作 (需後端 API: GET /ai-simulator/preview)',
    color: 'warning'
  }
}

// 模擬訓練過程 - 生成類似 Figma 設計的數據
let trainingInterval: ReturnType<typeof setInterval> | null = null

function simulateTraining() {
  if (trainingInterval) clearInterval(trainingInterval)

  // 訓練參數
  let currentEpoch = 0
  const maxEpoch = 1000
  const stepSize = 10 // 每次更新的 epoch 數
  let bestReward = 0.5

  trainingInterval = setInterval(() => {
    if (currentEpoch >= maxEpoch) {
      if (trainingInterval) clearInterval(trainingInterval)
      trainingStatus.value = 'finish'
      trainingResults.value = {
        reward: 0.98,
        actorLoss: -2.3,
        criticLoss: 0.002
      }
      return
    }

    currentEpoch += stepSize
    trainingEpoch.value = currentEpoch

    // 模擬 Reward 數據 (逐漸從 0.5 增長到 0.98，帶隨機波動)
    const progress = currentEpoch / maxEpoch
    const baseReward = 0.5 + (0.48 * progress)
    const noise = (Math.random() - 0.5) * 0.15
    const currentReward = Math.max(0.4, Math.min(1.1, baseReward + noise))

    // 更新 best reward
    if (currentReward > bestReward) {
      bestReward = currentReward
    }

    // Critic Loss: 從 0.35 下降到 0.002 (快速下降後趨於平穩)
    const criticBase = 0.35 * Math.exp(-progress * 3)
    const criticNoise = Math.random() * 0.02
    const criticLoss = Math.max(0.002, criticBase + criticNoise)

    // Actor Loss: 從 -1.2 下降到 -2.0 (帶較大波動)
    const actorBase = -1.2 - (0.8 * progress)
    const actorNoise = (Math.random() - 0.5) * 0.3
    const actorLoss = actorBase + actorNoise

    // 存儲數據
    trainingData.value.epochs.push(currentEpoch)
    trainingData.value.rewards.push(currentReward)
    trainingData.value.bestRewards.push(bestReward)
    trainingData.value.criticLosses.push(criticLoss)
    trainingData.value.actorLosses.push(actorLoss)

    // 計算移動平均
    trainingData.value.rewardsMA10 = calculateMA(trainingData.value.rewards, 10)
    trainingData.value.bestRewardsMA10 = calculateMA(trainingData.value.bestRewards, 10)

    // 更新顯示結果
    trainingResults.value = {
      reward: currentReward,
      actorLoss: actorLoss,
      criticLoss: criticLoss
    }

    // 更新圖表
    updateCharts()
  }, 50) // 50ms 更新一次，讓動畫流暢
}

// 初始化地圖
const initializeMap = async () => {
  if (map) {
    map.remove()
    map = null
  }

  await nextTick()
  const mapContainer = document.getElementById('aiSimulatorMap')
  if (!mapContainer) return

  try {
    mapboxgl.accessToken = mapAccessToken
    const initialStyle = (isOnline ? onlineStyle : offlineStyle) as string | mapboxgl.StyleSpecification | undefined

    map = new mapboxgl.Map({
      container: 'aiSimulatorMap',
      style: initialStyle,
      center: [120.997, 24.787], // 交大座標
      zoom: 16
    })
    map.addControl(new mapboxgl.NavigationControl())
  } catch (error) {
    console.error('Map initialization error:', error)
  }
}

// 監聽訓練狀態，重新初始化地圖
watch(trainingStatus, (newStatus) => {
  if (newStatus === 'idle') {
    destroyCharts()
    nextTick(() => initializeMap())
  }
})

onMounted(() => {
  initializeMap()
})

onUnmounted(() => {
  if (map) {
    map.remove()
    map = null
  }
  if (trainingInterval) {
    clearInterval(trainingInterval)
  }
  destroyCharts()
})
</script>

<style scoped>
.ai-simulator-page {
  padding: 24px;
  max-width: 1440px;
  margin: 0 auto;
}

.page-header {
  display: flex;
  align-items: center;
  gap: 24px;
  margin-bottom: 24px;
  flex-wrap: wrap;
}

.page-title {
  font-size: 40px;
  font-weight: 400;
  color: #000;
  margin: 0;
}

/* 警告橫幅 (Figma 277:986) */
.warning-banner {
  display: flex;
  align-items: center;
  gap: 8px;
  border: 1px solid rgba(185, 7, 7, 0.5);
  padding: 8px 16px;
  border-radius: 20px;
  font-size: 16px;
  color: rgba(255, 0, 0, 0.7);
}

.page-content {
  display: flex;
  gap: 24px;
  min-height: 700px;
}

/* 左側面板 */
.left-panel {
  width: 246px;
  flex-shrink: 0;
  background: #fff;
  border: 1px solid #000;
  border-radius: 20px;
  box-shadow: 4px 4px 20px rgba(0, 0, 0, 0.25);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.panel-header {
  background: #c7c7c7;
  padding: 12px 20px;
  font-size: 40px;
  font-weight: 500;
  color: #000;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.model-buttons {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 20px;
  flex: 1;
}

.model-btn {
  height: 55px;
  border-radius: 50px !important;
  font-size: 32px !important;
  text-transform: none;
}

/* NES 控制面板 */
.nes-controls {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 20px;
  flex: 1;
}

.model-select {
  margin-bottom: 8px;
}

.control-btn {
  height: 50px;
  border-radius: 50px !important;
  font-size: 18px !important;
  text-transform: none;
}

.panel-actions {
  display: flex;
  gap: 12px;
  padding: 20px;
  justify-content: center;
}

.action-btn {
  flex: 1;
  height: 40px;
  border-radius: 50px !important;
  text-transform: none;
}

/* Placeholder 內容 */
.placeholder-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  flex: 1;
  padding: 40px;
}

/* 右側面板 */
.right-panel {
  flex: 1;
  background: #fff;
  border: 2px solid #000;
  border-radius: 20px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

/* 地圖容器 */
.map-container {
  flex: 1;
  position: relative;
  min-height: 500px;
}

.map-view {
  width: 100%;
  height: 100%;
  min-height: 500px;
}

/* 色標 */
.color-bar {
  position: absolute;
  right: 20px;
  top: 100px;
  width: 45px;
  height: 300px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.color-gradient {
  width: 24px;
  height: 250px;
  background: linear-gradient(to bottom, red, orange, yellow, green, cyan, blue);
  border-radius: 4px;
}

.color-labels {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 250px;
  font-size: 11px;
  color: #333;
  position: absolute;
  right: 50px;
  top: 0;
}

/* Heatmap 控制 */
.heatmap-control {
  position: absolute;
  right: 20px;
  bottom: 20px;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 8px;
  padding: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.heatmap-switch {
  transform: scale(0.85);
}

.heatmap-select {
  max-width: 100px;
}

/* 訓練狀態 */
.training-status {
  font-size: 20px;
  margin-left: auto;
}

.training-status.running {
  color: #f00;
}

.training-status.finish {
  color: #4caf50;
}

/* 訓練內容 */
.training-content {
  display: flex;
  flex: 1;
  padding: 20px;
  gap: 24px;
}

.charts-section {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 16px;
  min-width: 0;
}

.chart-container {
  background: #fff;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 12px;
}

.main-chart {
  flex: 2;
}

.chart-title {
  font-size: 12px;
  color: #333;
  margin-bottom: 8px;
  text-align: center;
  font-weight: 500;
}

.chart-wrapper {
  height: 240px;
  position: relative;
}

.chart-wrapper.small {
  height: 150px;
}

.charts-row {
  display: flex;
  gap: 16px;
  flex: 1;
}

.charts-row .chart-container {
  flex: 1;
  min-width: 0;
}

/* 訓練資訊 */
.training-info {
  width: 280px;
  padding: 16px;
  flex-shrink: 0;
}

.info-item {
  font-size: 18px;
  margin-bottom: 8px;
}

.info-item.highlight {
  color: #006ab5;
  font-size: 20px;
}

.results-section {
  margin-top: 24px;
}

.results-title {
  font-size: 18px;
  font-weight: 500;
  margin-bottom: 12px;
}

.result-item {
  font-size: 16px;
  margin-bottom: 8px;
  padding-left: 16px;
}

/* 響應式 */
@media (max-width: 1024px) {
  .page-content {
    flex-direction: column;
  }

  .left-panel {
    width: 100%;
  }

  .model-buttons {
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
  }

  .model-btn {
    width: auto;
    min-width: 100px;
  }

  .training-content {
    flex-direction: column;
  }

  .training-info {
    width: 100%;
  }
}

@media (max-width: 768px) {
  .page-title {
    font-size: 28px;
  }

  .panel-header {
    font-size: 24px;
  }

  .charts-row {
    flex-direction: column;
  }
}
</style>
