<template>
  <div class="ai-simulator-page">
    <div class="page-header">
      <h1 class="page-title">AI Application Simulator</h1>
      <!-- 警告橫幅 (Figma 277:986) -->
      <div class="warning-banner">
        <v-icon color="warning" size="20">mdi-alert-circle</v-icon>
        <span>Note: All data is generated by the simulator.</span>
      </div>
    </div>

    <div class="page-content">
      <!-- 左側面板：Model List 或 NES 控制面板 -->
      <div class="left-panel">
        <!-- Model List 視圖 -->
        <template v-if="!selectedModel">
          <div class="panel-header">Model list</div>
          <div class="model-buttons">
            <v-btn
              v-for="model in modelList"
              :key="model.id"
              color="success"
              variant="elevated"
              class="model-btn"
              @click="selectModel(model.id)"
            >
              {{ model.name }}
            </v-btn>
          </div>
        </template>

        <!-- NES Model 控制面板 (Figma 277:465) -->
        <template v-else-if="selectedModel === 'nes'">
          <div class="panel-header">NES</div>
          <div class="nes-controls">
            <v-select
              v-model="nesModelSelect"
              :items="nesModelOptions"
              label="Model Select"
              density="compact"
              variant="outlined"
              class="model-select"
              hide-details
            />
            <v-btn
              :color="nesModelSelect ? 'success' : 'default'"
              :disabled="!nesModelSelect || trainingStatus === 'running'"
              variant="elevated"
              class="control-btn"
              @click="startPreTrain"
            >
              Pre-train
            </v-btn>
            <v-btn
              :color="trainingStatus === 'finish' ? 'warning' : 'default'"
              :disabled="trainingStatus !== 'finish'"
              variant="elevated"
              class="control-btn"
              @click="showPreview"
            >
              Preview
            </v-btn>
          </div>
          <div class="panel-actions">
            <v-btn color="primary" variant="outlined" class="action-btn" @click="goBack">
              BACK
            </v-btn>
            <v-btn
              v-if="trainingStatus === 'running'"
              color="error"
              variant="elevated"
              class="action-btn"
              @click="stopTraining"
            >
              STOP
            </v-btn>
            <v-btn
              v-else-if="trainingStatus === 'finish'"
              color="primary"
              variant="elevated"
              class="action-btn"
              @click="updateModel"
            >
              Update
            </v-btn>
            <v-btn
              v-else
              color="primary"
              variant="elevated"
              class="action-btn"
              @click="startTraining"
            >
              START
            </v-btn>
          </div>
        </template>

        <!-- 其他模型 placeholder -->
        <template v-else>
          <div class="panel-header">{{ selectedModel.toUpperCase() }}</div>
          <div class="placeholder-content">
            <v-icon size="48" color="grey">mdi-cog</v-icon>
            <p class="text-grey">功能開發中</p>
          </div>
          <div class="panel-actions">
            <v-btn color="primary" variant="outlined" class="action-btn" @click="goBack">
              BACK
            </v-btn>
          </div>
        </template>
      </div>

      <!-- 右側面板：Scene 或 Pre-Train Process -->
      <div class="right-panel">
        <!-- Scene 視圖 (無訓練時) -->
        <template v-if="trainingStatus !== 'running' && trainingStatus !== 'finish'">
          <div class="panel-header">Scene</div>
          <div class="map-container">
            <div id="aiSimulatorMap" class="map-view" />
            <!-- 色標 -->
            <div v-show="showHeatmap" class="color-bar">
              <div class="color-gradient" />
              <div class="color-labels">
                <span>-59.8 dBm</span>
                <span>-140.0 dBm</span>
              </div>
            </div>
            <!-- Heatmap 控制 -->
            <div class="heatmap-control">
              <v-switch
                v-model="showHeatmap"
                label="Heatmap"
                density="compact"
                hide-details
                class="heatmap-switch"
              />
              <v-select
                v-model="heatmapType"
                :items="['RSRP']"
                density="compact"
                class="heatmap-select"
                hide-details
              />
            </div>
          </div>
        </template>

        <!-- Pre-Train Process 視圖 (Figma 277:383) -->
        <template v-else>
          <div class="panel-header">
            Pre-Train Process
            <span :class="['training-status', trainingStatus]">
              Training Status: {{ trainingStatus }}
            </span>
          </div>
          <div class="training-content">
            <!-- 訓練圖表區域 -->
            <div class="charts-section">
              <div class="chart-placeholder main-chart">
                <p class="chart-title">Reward over Epochs (with MA10)</p>
                <div class="chart-area">
                  <v-icon size="32" color="grey">mdi-chart-line</v-icon>
                </div>
              </div>
              <div class="charts-row">
                <div class="chart-placeholder">
                  <p class="chart-title">Critic Loss over Epochs</p>
                  <div class="chart-area">
                    <v-icon size="24" color="grey">mdi-chart-line</v-icon>
                  </div>
                </div>
                <div class="chart-placeholder">
                  <p class="chart-title">Actor Loss over Epochs</p>
                  <div class="chart-area">
                    <v-icon size="24" color="grey">mdi-chart-line</v-icon>
                  </div>
                </div>
              </div>
            </div>
            <!-- 訓練資訊 -->
            <div class="training-info">
              <p class="info-item highlight">Loss Function: Self-defined</p>
              <p class="info-item">Epoch: {{ trainingEpoch }}/1000</p>
              <div class="results-section">
                <p class="results-title">Training Results:</p>
                <p class="result-item">Reward: {{ trainingResults.reward }}</p>
                <p class="result-item">Actor Loss: {{ trainingResults.actorLoss }}</p>
                <p class="result-item">Critic Loss: {{ trainingResults.criticLoss }}</p>
              </div>
            </div>
          </div>
        </template>
      </div>
    </div>

    <!-- 提示訊息 -->
    <v-snackbar v-model="snackbar.show" :color="snackbar.color" timeout="3000" location="top">
      {{ snackbar.text }}
    </v-snackbar>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useRoute } from 'vue-router'
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'

const route = useRoute()
const config = useRuntimeConfig()
const isOnline = config.public?.isOnline

// 地圖相關
let map: mapboxgl.Map | null = null
const mapAccessToken = 'pk.eyJ1IjoiZGFyaXVzbHVuZyIsImEiOiJjbHk3MWhvZW4wMTl6MmlxMnVhNzI3cW0yIn0.WGvtamOAfwfk3Ha4KsL3BQ'
const onlineStyle = 'mapbox://styles/mapbox/streets-v12'
const offlineStyle = config.public?.offlineMapboxGLJSURL

// Model 列表 (Figma 277:952)
const modelList = [
  { id: 'nes', name: 'NES' },
  { id: 'positioning', name: 'Positioning' },
  { id: 'im', name: 'IM' },
  { id: 'mro', name: 'MRO' },
  { id: 'rs', name: 'RS' },
  { id: 'bc', name: 'BC' }
]

const selectedModel = ref<string | null>(null)

// NES Model 控制 (Figma 277:465)
const nesModelSelect = ref<string | null>(null)
const nesModelOptions = ['Model 1', 'Model 2', 'Model 3']

// 訓練狀態
type TrainingStatus = 'idle' | 'running' | 'finish'
const trainingStatus = ref<TrainingStatus>('idle')
const trainingEpoch = ref(0)
const trainingResults = ref({
  reward: 0,
  actorLoss: 0,
  criticLoss: 0
})

// 場景選項 (Figma 277:592)
const sceneOptions = ['None', '上班', '下班', '上課1/隨機', '上課2/同步']
const selectedScene = ref('None')

// Heatmap 控制
const showHeatmap = ref(false)
const heatmapType = ref('RSRP')

const snackbar = ref({ show: false, text: '', color: 'info' })

// 選擇模型
function selectModel(modelId: string) {
  selectedModel.value = modelId
  trainingStatus.value = 'idle'
  trainingEpoch.value = 0
  nesModelSelect.value = null
}

// 返回 Model List
function goBack() {
  selectedModel.value = null
  trainingStatus.value = 'idle'
  trainingEpoch.value = 0
  nesModelSelect.value = null
  // 重新初始化地圖
  nextTick(() => initializeMap())
}

// 開始預訓練
function startPreTrain() {
  if (!nesModelSelect.value) return
  snackbar.value = {
    show: true,
    text: 'Pre-train 功能尚未實作',
    color: 'warning'
  }
}

// 開始訓練
function startTraining() {
  if (!nesModelSelect.value) {
    snackbar.value = {
      show: true,
      text: '請先選擇模型',
      color: 'warning'
    }
    return
  }
  trainingStatus.value = 'running'
  trainingEpoch.value = 0
  // 模擬訓練過程
  simulateTraining()
}

// 停止訓練
function stopTraining() {
  trainingStatus.value = 'idle'
  snackbar.value = {
    show: true,
    text: '訓練已停止',
    color: 'info'
  }
}

// 更新模型
function updateModel() {
  snackbar.value = {
    show: true,
    text: 'Update 功能尚未實作 (需後端 API)',
    color: 'warning'
  }
}

// 顯示預覽
function showPreview() {
  snackbar.value = {
    show: true,
    text: 'Preview 功能尚未實作',
    color: 'warning'
  }
}

// 模擬訓練過程 (placeholder)
let trainingInterval: ReturnType<typeof setInterval> | null = null
function simulateTraining() {
  if (trainingInterval) clearInterval(trainingInterval)

  trainingInterval = setInterval(() => {
    if (trainingEpoch.value >= 1000) {
      if (trainingInterval) clearInterval(trainingInterval)
      trainingStatus.value = 'finish'
      trainingResults.value = {
        reward: 0.98,
        actorLoss: -2.3,
        criticLoss: 0.002
      }
      return
    }
    trainingEpoch.value += 50
    // 模擬結果更新
    trainingResults.value = {
      reward: Math.min(0.98, trainingEpoch.value / 1000),
      actorLoss: -2.3 + Math.random() * 0.2,
      criticLoss: Math.max(0.002, 0.3 - trainingEpoch.value / 3500)
    }
  }, 100)
}

// 初始化地圖
const initializeMap = async () => {
  if (map) {
    map.remove()
    map = null
  }

  await nextTick()
  const mapContainer = document.getElementById('aiSimulatorMap')
  if (!mapContainer) return

  try {
    mapboxgl.accessToken = mapAccessToken
    const initialStyle = (isOnline ? onlineStyle : offlineStyle) as string | mapboxgl.StyleSpecification | undefined

    map = new mapboxgl.Map({
      container: 'aiSimulatorMap',
      style: initialStyle,
      center: [120.997, 24.787], // 交大座標
      zoom: 16
    })
    map.addControl(new mapboxgl.NavigationControl())
  } catch (error) {
    console.error('Map initialization error:', error)
  }
}

// 監聽訓練狀態，重新初始化地圖
watch(trainingStatus, (newStatus) => {
  if (newStatus === 'idle') {
    nextTick(() => initializeMap())
  }
})

onMounted(() => {
  initializeMap()
})

onUnmounted(() => {
  if (map) {
    map.remove()
    map = null
  }
  if (trainingInterval) {
    clearInterval(trainingInterval)
  }
})
</script>

<style scoped>
.ai-simulator-page {
  padding: 24px;
  max-width: 1440px;
  margin: 0 auto;
}

.page-header {
  display: flex;
  align-items: center;
  gap: 24px;
  margin-bottom: 24px;
  flex-wrap: wrap;
}

.page-title {
  font-size: 40px;
  font-weight: 400;
  color: #000;
  margin: 0;
}

/* 警告橫幅 (Figma 277:986) */
.warning-banner {
  display: flex;
  align-items: center;
  gap: 8px;
  border: 1px solid rgba(185, 7, 7, 0.5);
  padding: 8px 16px;
  border-radius: 20px;
  font-size: 16px;
  color: rgba(255, 0, 0, 0.7);
}

.page-content {
  display: flex;
  gap: 24px;
  min-height: 700px;
}

/* 左側面板 */
.left-panel {
  width: 246px;
  flex-shrink: 0;
  background: #fff;
  border: 1px solid #000;
  border-radius: 20px;
  box-shadow: 4px 4px 20px rgba(0, 0, 0, 0.25);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.panel-header {
  background: #c7c7c7;
  padding: 12px 20px;
  font-size: 40px;
  font-weight: 500;
  color: #000;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.model-buttons {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 20px;
  flex: 1;
}

.model-btn {
  height: 55px;
  border-radius: 50px !important;
  font-size: 32px !important;
  text-transform: none;
}

/* NES 控制面板 */
.nes-controls {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 20px;
  flex: 1;
}

.model-select {
  margin-bottom: 8px;
}

.control-btn {
  height: 50px;
  border-radius: 50px !important;
  font-size: 18px !important;
  text-transform: none;
}

.panel-actions {
  display: flex;
  gap: 12px;
  padding: 20px;
  justify-content: center;
}

.action-btn {
  flex: 1;
  height: 40px;
  border-radius: 50px !important;
  text-transform: none;
}

/* Placeholder 內容 */
.placeholder-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  flex: 1;
  padding: 40px;
}

/* 右側面板 */
.right-panel {
  flex: 1;
  background: #fff;
  border: 2px solid #000;
  border-radius: 20px;
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

/* 地圖容器 */
.map-container {
  flex: 1;
  position: relative;
  min-height: 500px;
}

.map-view {
  width: 100%;
  height: 100%;
  min-height: 500px;
}

/* 色標 */
.color-bar {
  position: absolute;
  right: 20px;
  top: 100px;
  width: 45px;
  height: 300px;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.color-gradient {
  width: 24px;
  height: 250px;
  background: linear-gradient(to bottom, red, orange, yellow, green, cyan, blue);
  border-radius: 4px;
}

.color-labels {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 250px;
  font-size: 11px;
  color: #333;
  position: absolute;
  right: 50px;
  top: 0;
}

/* Heatmap 控制 */
.heatmap-control {
  position: absolute;
  right: 20px;
  bottom: 20px;
  background: rgba(255, 255, 255, 0.95);
  border-radius: 8px;
  padding: 12px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.heatmap-switch {
  transform: scale(0.85);
}

.heatmap-select {
  max-width: 100px;
}

/* 訓練狀態 */
.training-status {
  font-size: 20px;
  margin-left: auto;
}

.training-status.running {
  color: #f00;
}

.training-status.finish {
  color: #4caf50;
}

/* 訓練內容 */
.training-content {
  display: flex;
  flex: 1;
  padding: 20px;
  gap: 24px;
}

.charts-section {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.chart-placeholder {
  background: #f9f9f9;
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 12px;
}

.main-chart {
  flex: 2;
}

.charts-row {
  display: flex;
  gap: 16px;
  flex: 1;
}

.charts-row .chart-placeholder {
  flex: 1;
}

.chart-title {
  font-size: 12px;
  color: #666;
  margin-bottom: 8px;
  text-align: center;
}

.chart-area {
  height: 100%;
  min-height: 80px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: #fff;
  border-radius: 4px;
}

/* 訓練資訊 */
.training-info {
  width: 280px;
  padding: 16px;
}

.info-item {
  font-size: 18px;
  margin-bottom: 8px;
}

.info-item.highlight {
  color: #006ab5;
  font-size: 20px;
}

.results-section {
  margin-top: 24px;
}

.results-title {
  font-size: 18px;
  font-weight: 500;
  margin-bottom: 12px;
}

.result-item {
  font-size: 16px;
  margin-bottom: 8px;
  padding-left: 16px;
}

/* 響應式 */
@media (max-width: 1024px) {
  .page-content {
    flex-direction: column;
  }

  .left-panel {
    width: 100%;
  }

  .model-buttons {
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: center;
  }

  .model-btn {
    width: auto;
    min-width: 100px;
  }

  .training-content {
    flex-direction: column;
  }

  .training-info {
    width: 100%;
  }
}

@media (max-width: 768px) {
  .page-title {
    font-size: 28px;
  }

  .panel-header {
    font-size: 24px;
  }
}
</style>
