"""initial migration

Revision ID: 52d56e498b3c
Revises: 
Create Date: 2025-08-06 15:51:44.744763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d56e498b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('bandwidth', sa.Float(), nullable=False),
    sa.Column('tx_power', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('primitive_AI_models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('primitive_DT_AI_models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('grafana_folder_id', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lon', sa.Double(), nullable=False),
    sa.Column('margin', sa.Integer(), nullable=False),
    sa.Column('rotation_offset', sa.Float(), nullable=True),
    sa.Column('lat_offset', sa.Float(), nullable=True),
    sa.Column('lon_offset', sa.Float(), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column('rsrp_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.Column('throughput_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.Column('rsrp_dt_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.Column('throughput_dt_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('grafana_folder_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.Column('grafana_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('grafana_user_id')
    )
    op.create_table('AI_models',
    sa.Column('AI_model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('AI_model_id')
    )
    op.create_table('CUs',
    sa.Column('CU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('CU_id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_cu_pid_name')
    )
    op.create_table('DT_AI_models',
    sa.Column('DT_AI_model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('DT_AI_model_id')
    )
    op.create_table('evaluations',
    sa.Column('eval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('rsrp_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.Column('throughput_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.Column('rsrp_dt_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.Column('throughput_dt_status', sa.Enum('IDLE', 'WAITING', 'FAILURE', 'SUCCESS', 'DISCARDED', name='heatmapstate'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('eval_id')
    )
    op.create_table('maps',
    sa.Column('map_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('MinIO_map_for_aodt', sa.String(length=255), nullable=True),
    sa.Column('MinIO_map_for_frontend', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('map_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('user_projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'OWNER', name='projectrole'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('DUs',
    sa.Column('DU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CU_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CU_id'], ['CUs.CU_id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('DU_id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_du_pid_name')
    )
    op.create_table('RU_caches',
    sa.Column('RU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('eval_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('bandwidth', sa.Float(), nullable=False),
    sa.Column('tx_power', sa.Float(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('opening_angle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['eval_id'], ['evaluations.eval_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('RU_id'),
    sa.UniqueConstraint('eval_id', 'name', name='uq_ru_cache_pid_name')
    )
    op.create_table('RUs',
    sa.Column('RU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('DU_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('bandwidth', sa.Float(), nullable=False),
    sa.Column('tx_power', sa.Float(), nullable=False),
    sa.Column('roll', sa.Integer(), nullable=False),
    sa.Column('opening_angle', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['DU_id'], ['DUs.DU_id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.brand_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('RU_id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_ru_pid_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RUs')
    op.drop_table('RU_caches')
    op.drop_table('DUs')
    op.drop_table('user_projects')
    op.drop_table('maps')
    op.drop_table('evaluations')
    op.drop_table('DT_AI_models')
    op.drop_table('CUs')
    op.drop_table('AI_models')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('primitive_DT_AI_models')
    op.drop_table('primitive_AI_models')
    op.drop_table('brands')
    # ### end Alembic commands ###
