"""add ru metrics

Revision ID: 9afad3f08c9a
Revises: 52d56e498b3c
Create Date: 2025-08-11 15:55:03.446984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afad3f08c9a'
down_revision = '52d56e498b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ran_device_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_or_AI_name', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('api_source', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ran_device_metrics')
    # ### end Alembic commands ###
