"""add_ru_column_tilt

Revision ID: caf077ba0e9b
Revises: d4b4769bf511
Create Date: 2025-10-23 15:15:25.851073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf077ba0e9b'
down_revision = 'd4b4769bf511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RU_caches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tilt', sa.Integer(), nullable=False))

    with op.batch_alter_table('RUs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tilt', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('RUs', schema=None) as batch_op:
        batch_op.drop_column('tilt')

    with op.batch_alter_table('RU_caches', schema=None) as batch_op:
        batch_op.drop_column('tilt')

    # ### end Alembic commands ###
